name: module-tagging

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup script runtime
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Gather files changed
        id: files-changed
        uses: trilom/file-changes-action@1.2.4
        with:
          fileOutput: 'json'

      - name: Filter for files
        run: deno run --allow-read .github/scripts/tag-modules.ts
